version: '3.7'

networks:
  web:
    external: true
  internal:
    external: false

services:
  web:
    build: .
    command: gunicorn ${RELOAD} film.wsgi -b 0.0.0.0:8001
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - MARKETING_SITE_URL=${MARKETING_SITE_URL}
      - EMAIL_BACKEND=${EMAIL_BACKEND}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
      - SUBSCRIPTION_TRIAL=${SUBSCRIPTION_TRIAL}
      - SUBSCRIPTION_TRIAL_DURATION=${SUBSCRIPTION_TRIAL_DURATION}
      - PADDLE_LIVE_MODE=${PADDLE_LIVE_MODE}
      - PADDLE_VENDOR_ID=${PADDLE_VENDOR_ID}
      - PADDLE_VENDOR_AUTH_CODE=${PADDLE_VENDOR_AUTH_CODE}
      - PADDLE_STANDARD_MONTHLY=${PADDLE_STANDARD_MONTHLY}
      - PADDLE_STANDARD_ANNUAL=${PADDLE_STANDARD_ANNUAL}
      - PADDLE_PUBLIC_KEY=${PADDLE_PUBLIC_KEY}
      - DBBACKUP_STORAGE=${DBBACKUP_STORAGE}
      - DBBACKUP_STORAGE_OPTIONS=${DBBACKUP_STORAGE_OPTIONS}
    volumes:
      - .:/code
    ports:
      - '127.0.0.1:8001:8001'
      - '8383:8383'
    networks:
      - internal
      - web
    labels:
      - traefik.http.routers.web.rule=Host(`app.cassettenest.com`)
      - traefik.http.routers.web.tls=true
      - traefik.http.routers.web.tls.certresolver=lets-encrypt
      - traefik.port=8001
      - traefik.http.routers.web.middlewares=hsts
      - traefik.http.middlewares.hsts.headers.stsSeconds=15552000
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    labels:
      - traefik.enable=false
    networks:
      - internal
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
