version: '3.7'

networks:
  web:
    external: true
  internal:
    external: false

services:
  web:
    build: .
    command: gunicorn ${RELOAD} film.wsgi -b 0.0.0.0:8001
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - EMAIL_BACKEND=${EMAIL_BACKEND}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
      - STRIPE_LIVE_PUBLIC_KEY=${STRIPE_LIVE_PUBLIC_KEY}
      - STRIPE_LIVE_SECRET_KEY=${STRIPE_LIVE_SECRET_KEY}
      - STRIPE_TEST_PUBLIC_KEY=${STRIPE_TEST_PUBLIC_KEY}
      - STRIPE_TEST_SECRET_KEY=${STRIPE_TEST_SECRET_KEY}
      - STRIPE_LIVE_MODE=${STRIPE_LIVE_MODE}
      - DJSTRIPE_WEBHOOK_SECRET=${DJSTRIPE_WEBHOOK_SECRET}
    volumes:
      - .:/code
    ports:
      - '8001:8001'
    networks:
      - internal
      - web
    labels:
      - traefik.backend=cassettenest_web_1
      - traefik.frontend.rule=Host:app.cassettenest.com
      - traefik.docker.network=web
      - traefik.port=8001
      - traefik.frontend.headers.customResponseHeaders=Strict-Transport-Security:15552000
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    labels:
      - traefik.enable=false
    networks:
      - internal
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
