#!/bin/sh

# Restore the local database after verifying the production database backup.

# Set variables
temp_folder="${HOME}/Code/cassettenest/backups"

# Reload local database.
venv/bin/python manage.py dbrestore -q --noinput -z -i local.psql.gz

# Delete the production backup we verified from the local machine.
rm ${temp_folder}/cassettenest_*.psql.bin.gz
