#!/bin/sh

# Load the latest production database backup locally.

# Set variables
temp_folder="${HOME}/Code/cassettenest/backups"
now=$(date +"%F")
latest_backup="cassettenest_${now}"

# Create the temp folder if necessary.
mkdir -p temp_folder

# Delete existing local backup if it exists.
rm ${temp_folder}/local.dump 2> /dev/null

# Backup local database
docker-compose exec -T db pg_dump --format=custom -U cassette_nest cassette_nest > ${temp_folder}/local.dump

# Get today’s production database backup.
s3cmd get s3://cassettenest/backups-daily/${latest_backup}.dump.enc ${temp_folder}/${latest_backup}.dump

# Load the production backup into our local Docker.
docker-compose exec -T db pg_restore -U cassette_nest -d cassette_nest --clean < ${temp_folder}/${latest_backup}.dump
