# Generated by Django 2.0.2 on 2018-03-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="filmname",
            name="slug",
            field=models.SlugField(default="", unique=True),
            preserve_default=False,
        ),
    ]
