# Generated by Django 2.0.2 on 2018-03-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_filmname_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturer",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
