# Generated by Django 2.0.2 on 2018-03-04 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_auto_20180304_0013"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="filmname",
            options={"ordering": ["name"]},
        ),
    ]
