# Generated by Django 2.0.2 on 2018-03-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_auto_20180304_0033"),
    ]

    operations = [
        migrations.AddField(
            model_name="filmname",
            name="type",
            field=models.CharField(
                choices=[
                    ("c41", "C41 Color"),
                    ("bw", "Black and White"),
                    ("e6", "E6 Color Reversal"),
                ],
                default="c41",
                max_length=20,
            ),
        ),
    ]
