# Generated by Django 2.0.2 on 2018-03-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_film_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='status',
            field=models.CharField(choices=[('storage', 'Storage'), ('loaded', 'Loaded'), ('shot', 'Shot'), ('processing', 'Processing'), ('processed', 'Processed'), ('scanned', 'Scanned'), ('archived', 'Archived')], default='storage', max_length=20),
        ),
    ]
