# Generated by Django 2.0.2 on 2018-03-30 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_camera"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="camera",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.Camera",
            ),
        ),
    ]
