# Generated by Django 2.0.2 on 2018-04-06 13:27

from django.db import migrations


class Migration(migrations.Migration):
    atomic=False

    dependencies = [
        ('inventory', '0010_film_camera'),
    ]

    operations = [
        migrations.RenameModel('Film', 'Roll'),
        migrations.RenameModel('FilmName', 'Film')
    ]
