# Generated by Django 2.0.2 on 2018-04-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_auto_20180427_0052"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roll",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="A unique roll code (per year)",
                max_length=100,
                unique_for_year="started_on",
            ),
        ),
    ]
