# Generated by Django 2.0.2 on 2018-04-28 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20180427_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='speed',
            new_name='iso',
        ),
    ]
