# Generated by Django 2.0.2 on 2018-05-28 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_auto_20180514_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['manufacturer__name', 'name']},
        ),
    ]
