# Generated by Django 2.0.2 on 2018-05-28 20:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0021_auto_20180528_1203'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='camera',
            unique_together={('owner', 'name')},
        ),
    ]
