# Generated by Django 2.0.2 on 2018-08-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='status',
            field=models.CharField(choices=[('01_storage', 'Storage'), ('02_loaded', 'Loaded'), ('03_shot', 'Shot'), ('04_processing', 'Processing'), ('05_processed', 'Processed'), ('06_scanned', 'Scanned'), ('07_archived', 'Archived')], default='01_storage', max_length=20),
        ),
    ]
