# Generated by Django 2.1 on 2018-09-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0027_auto_20180829_0926"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="cameras",
            field=models.ManyToManyField(to="inventory.Camera"),
        ),
    ]
