# Generated by Django 2.1 on 2018-09-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_project_cameras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cameras',
            field=models.ManyToManyField(blank=True, null=True, to='inventory.Camera'),
        ),
    ]
