# Generated by Django 2.1 on 2018-09-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0029_auto_20180911_0832"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="cameras",
            field=models.ManyToManyField(blank=True, to="inventory.Camera"),
        ),
    ]
