# Generated by Django 2.1 on 2018-09-13 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_auto_20180911_0839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'ordering': ['-status', 'name']},
        ),
    ]
