# Generated by Django 2.1 on 2018-12-05 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_journal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['date']},
        ),
        migrations.AlterUniqueTogether(
            name='journal',
            unique_together={('roll', 'date')},
        ),
    ]
