# Generated by Django 2.1 on 2018-12-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0034_auto_20181205_0817"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journal",
            name="owner",
        ),
    ]
