# Generated by Django 2.1 on 2018-12-06 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0035_remove_journal_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journal",
            options={
                "ordering": ["date"],
                "verbose_name": "journal entry",
                "verbose_name_plural": "journal entries",
            },
        ),
    ]
