# Generated by Django 2.1 on 2018-12-07 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0036_auto_20181206_0832"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="journal",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
