# Generated by Django 2.1 on 2019-02-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0038_auto_20190203_1015"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="url",
            field=models.URLField(blank=True, verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="url",
            field=models.URLField(blank=True, verbose_name="URL"),
        ),
    ]
