# Generated by Django 2.2.1 on 2019-05-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_auto_20190416_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='code',
            field=models.CharField(blank=True, help_text='A unique identifier (per year)', max_length=100),
        ),
    ]
