# Generated by Django 2.2.3 on 2019-07-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0042_auto_20190531_0927"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
