# Generated by Django 3.0.3 on 2020-04-18 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0049_auto_20200412_1223"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cameraback",
            name="camera",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="camera_backs",
                to="inventory.Camera",
            ),
        ),
    ]
