# Generated by Django 3.0.5 on 2020-04-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0050_auto_20200418_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraback',
            name='format',
            field=models.CharField(blank=True, choices=[('135', '35mm'), ('120', '120')], default='120', max_length=20),
        ),
    ]
