# Generated by Django 3.0.7 on 2020-10-17 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0054_auto_20201016_1238'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='film',
            unique_together={('manufacturer', 'name', 'format',)},
        ),
    ]
