# Generated by Django 3.1.4 on 2021-01-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0056_auto_20201228_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription',
            field=models.CharField(choices=[('annual', 'Annual'), ('none', 'None'), ('monthly', 'Monthly')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription_status',
            field=models.CharField(choices=[('none', 'Never had a subscription'), ('pending', 'Pending update'), ('active', 'Subscribed'), ('error', 'Payment error'), ('canceling', 'Scheduled to cancel'), ('canceled', 'Canceled')], default='none', max_length=20),
        ),
    ]
