# Generated by Django 3.1.5 on 2021-01-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0057_auto_20210111_1232"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="subscription",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("annual", "Annual"),
                    ("monthly", "Monthly"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
