# Generated by Django 3.1.4 on 2021-01-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0059_auto_20210126_1753"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="friend",
            field=models.BooleanField(
                default=False, help_text="This account doesn’t need a subscription."
            ),
        ),
    ]
