# Generated by Django 3.2.2 on 2021-05-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0063_frame"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frame",
            name="aperture",
            field=models.CharField(
                blank=True,
                help_text="A custom value here will always override the value in the dropdown.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="frame",
            name="shutter_speed",
            field=models.CharField(
                blank=True,
                help_text="A custom value here will always override the value in the dropdown.",
                max_length=20,
            ),
        ),
    ]
