# Generated by Django 3.2.2 on 2021-05-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0064_auto_20210512_1711"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frame",
            name="number",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
