# Generated by Django 3.2.2 on 2021-05-13 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0065_alter_frame_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='frame',
            unique_together={('roll', 'number')},
        ),
    ]
