# Generated by Django 3.2.2 on 2021-05-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0066_alter_frame_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='aperture',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='frame',
            name='shutter_speed',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
