# Generated by Django 3.2.4 on 2021-06-29 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0069_auto_20210629_1155"),
    ]

    operations = [
        migrations.AddField(
            model_name="film",
            name="stock",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.stock",
            ),
        ),
    ]
