# Generated by Django 3.2.4 on 2021-06-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0070_film_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='type',
            field=models.CharField(choices=[('c41', 'C41 Color'), ('bw', 'Black and White'), ('e6', 'E6 Color Reversal')], default='c41', max_length=20),
        ),
    ]
