# Generated by Django 3.2.6 on 2021-08-13 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0074_alter_film_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="film",
            unique_together={("stock", "format")},
        ),
    ]
