# Generated by Django 4.1.6 on 2023-02-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0081_profile_color_preference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="color_preference",
            field=models.CharField(
                choices=[("auto", "Automatic"), ("light", "Light"), ("dark", "Dark")],
                default="auto",
                help_text="Note: Automatic mode requires JavaScript to work 😢",
                max_length=5,
            ),
        ),
    ]
