# Generated by Django 4.2 on 2023-04-03 15:42

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0082_alter_profile_color_preference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="timezone",
            field=models.CharField(
                blank=True,
                choices=settings.TIME_ZONES,
                default=settings.TIME_ZONE,
                max_length=40,
            ),
        ),
    ]
