# Generated by Django 4.2 on 2023-04-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0083_alter_profile_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="color_preference",
            field=models.CharField(
                choices=[("auto", "Automatic"), ("light", "Light"), ("dark", "Dark")],
                default="auto",
                max_length=5,
            ),
        ),
    ]
