# Generated by Django 4.2 on 2023-04-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0084_alter_profile_color_preference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roll",
            name="push_pull",
            field=models.CharField(
                blank=True,
                choices=[
                    ("-2", "Pull 2 stops"),
                    ("-1", "Pull 1 stop"),
                    ("+1", "Push 1 stop"),
                    ("+2", "Push 2 stops"),
                    ("+3", "Push 3 stops"),
                ],
                help_text="Push (postive) or pull (negative) by this many stops",
                max_length=2,
                verbose_name="Push/Pull",
            ),
        ),
    ]
