# Generated by Django 4.2.5 on 2023-09-10 13:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0085_alter_roll_push_pull"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="camera",
            options={"ordering": ["status", "name"]},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-status"]},
        ),
    ]
