# Generated by Django 4.2.6 on 2023-11-03 22:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0086_alter_camera_options_alter_project_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="friend",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="paddle_cancel_url",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="paddle_cancellation_date",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="paddle_subscription_id",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="paddle_subscription_plan_id",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="paddle_update_url",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="paddle_user_id",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="subscription_status",
        ),
    ]
