name: Django Tests and Coverage
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest

    # Set things up and run the tests.
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.5.0
        with:
          node-version: 18
      - name: Install dependencies, run tests, generate report
        run: |
          python3 -m venv --prompt . venv
          venv/bin/pip install -U pip setuptools wheel
          venv/bin/python -m pip install -r requirements.txt
          venv/bin/python manage.py migrate --noinput
          npm install
          npm run build
          venv/bin/playwright install
          venv/bin/python manage.py collectstatic --noinput
          venv/bin/pytest -n auto --cov=inventory --cov-report=xml
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: ${{ secrets.DEBUG }}
          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
          CSRF_TRUSTED_ORIGINS: ${{ secrets.CSRF_TRUSTED_ORIGINS }}
          MARKETING_SITE_URL: ${{ secrets.MARKETING_SITE_URL }}
          EMAIL_BACKEND: ${{ secrets.EMAIL_BACKEND }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          EMAIL_USE_TLS: ${{ secrets.EMAIL_USE_TLS }}
          KOFI_VERIFICATION_TOKEN: ${{ secrets.KOFI_VERIFICATION_TOKEN }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_SAMPLE_RATE: ${{ env.SENTRY_SAMPLE_RATE }}
          DEFAULT_FROM_EMAIL: ${{ env.DEFAULT_FROM_EMAIL }}
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-results
          path: test-results/
          retention-days: 2
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
